-- Converted from MySQL/MariaDB phpMyAdmin dump to PostgreSQL/Supabase-compatible SQL

-- Original file: Pasted text(7).txt

-- Notes: MySQL ENGINE/CHARSET/COLLATE/ON UPDATE syntax was removed or converted.

BEGIN;

SET TIME ZONE 'UTC';


-- Tables

CREATE TABLE IF NOT EXISTS public.addresses (
  address_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 6) NOT NULL,
  user_id integer DEFAULT NULL,
  floor_unit_number varchar(50) DEFAULT NULL,
  region varchar(100) DEFAULT NULL,
  province varchar(100) DEFAULT NULL,
  city_municipality varchar(100) DEFAULT NULL,
  barangay varchar(100) DEFAULT NULL,
  street varchar(255) DEFAULT NULL,
  other_notes text DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.categories (
  category_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 7) NOT NULL,
  category_name varchar(255) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  status integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.conversations (
  conversation_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
  buyer_id integer NOT NULL,
  seller_id integer NOT NULL,
  order_id integer DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.conversation_messages (
  message_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 8) NOT NULL,
  conversation_id integer NOT NULL,
  sender_id integer NOT NULL,
  message_text text NOT NULL,
  is_read smallint NOT NULL DEFAULT 0,
  read_at timestamp DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.delivery_partners (
  partner_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 11) NOT NULL,
  user_id integer DEFAULT NULL,
  full_name varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  phone varchar(20) NOT NULL,
  vehicle_type varchar(50) NOT NULL,
  plate_number varchar(50) NOT NULL,
  region varchar(100) NOT NULL,
  province varchar(100) NOT NULL,
  city varchar(100) NOT NULL,
  barangay varchar(100) NOT NULL,
  street varchar(255) NOT NULL,
  drivers_license_path varchar(255) NOT NULL,
  gov_id_path varchar(255) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.notifications (
  notification_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 82) NOT NULL,
  user_id integer NOT NULL,
  order_id integer DEFAULT NULL,
  title varchar(150) NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL DEFAULT 'order' CHECK (notification_type IN ('order','system','promo')),
  is_read smallint NOT NULL DEFAULT 0,
  read_at timestamp DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.orders (
  order_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 49) NOT NULL,
  user_id integer DEFAULT NULL,
  reference varchar(20) DEFAULT NULL,
  subtotal decimal(10,2) NOT NULL,
  shipping_fee decimal(10,2) NOT NULL,
  tax_amount decimal(10,2) NOT NULL,
  total_amount varchar(100) DEFAULT NULL,
  cash_type varchar(20) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  status integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.order_items (
  order_items_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 80) NOT NULL,
  product_id integer NOT NULL,
  user_id integer NOT NULL,
  suborder_id integer DEFAULT NULL,
  quantity integer NOT NULL,
  variant_type text NOT NULL DEFAULT 'none' CHECK (variant_type IN ('none','sizes','colors')),
  variant_value varchar(255) DEFAULT NULL,
  reference varchar(255) NOT NULL,
  status integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.order_suborders (
  suborder_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 48) NOT NULL,
  order_id integer NOT NULL,
  seller_id integer NOT NULL,
  reference varchar(255) NOT NULL,
  status integer NOT NULL DEFAULT 1,
  subtotal decimal(10,2) NOT NULL DEFAULT 0.00,
  shipping_fee decimal(10,2) NOT NULL DEFAULT 0.00,
  tax_amount decimal(10,2) NOT NULL DEFAULT 0.00,
  total_amount decimal(10,2) NOT NULL DEFAULT 0.00,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  pickup_status smallint NOT NULL DEFAULT 0,
  pickup_rider_id integer DEFAULT NULL,
  pickup_claimed_at timestamp DEFAULT NULL,
  pickup_completed_at timestamp DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS public.payments (
  payment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id integer DEFAULT NULL,
  payment_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  payment_amount integer DEFAULT NULL,
  status integer DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS public.products (
  product_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 85) NOT NULL,
  user_id integer DEFAULT NULL,
  category_id integer DEFAULT NULL,
  product_name varchar(255) DEFAULT NULL,
  description text DEFAULT NULL,
  price decimal(10,2) DEFAULT NULL,
  qty integer DEFAULT NULL,
  variant_type text NOT NULL DEFAULT 'none' CHECK (variant_type IN ('none','sizes','colors')),
  variant_values text DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  status integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.product_attachments (
  product_attachment_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 108) NOT NULL,
  product_id integer DEFAULT NULL,
  attachment varchar(255) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  status integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.product_reviews (
  review_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL,
  product_id integer NOT NULL,
  user_id integer NOT NULL,
  order_items_id integer DEFAULT NULL,
  reference varchar(255) DEFAULT NULL,
  rating smallint NOT NULL,
  comment text NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.reviews (
  review_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id integer NOT NULL,
  product_id integer NOT NULL,
  user_id integer NOT NULL,
  rating smallint NOT NULL CHECK (rating between 1 and 5),
  comment text DEFAULT NULL,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.roles (
  role_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
  name varchar(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS public.seller_details (
  seller_detail_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 13) NOT NULL,
  user_id integer NOT NULL,
  store_name varchar(255) NOT NULL,
  description text DEFAULT NULL,
  region varchar(100) DEFAULT NULL,
  province varchar(100) DEFAULT NULL,
  city varchar(100) DEFAULT NULL,
  barangay varchar(100) DEFAULT NULL,
  street varchar(255) DEFAULT NULL,
  gov_id_path varchar(255) DEFAULT NULL,
  business_permit_path varchar(255) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 54) NOT NULL,
  role_id integer DEFAULT 2,
  firstname varchar(255) DEFAULT NULL,
  lastname varchar(255) DEFAULT NULL,
  email varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  phone varchar(20) DEFAULT NULL,
  email_verified smallint DEFAULT 0,
  email_verified_at timestamp DEFAULT NULL,
  email_code_hash varchar(255) DEFAULT NULL,
  email_code_expires_at timestamp DEFAULT NULL,
  email_code_attempts smallint DEFAULT 0,
  email_code_last_sent_at timestamp DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  status integer DEFAULT 1,
  otp_last_sent_at timestamp DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS public.wishlists (
  wishlist_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 7) NOT NULL,
  user_id integer NOT NULL,
  product_id integer NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- Data

--
-- Dumping data for table addresses
--

INSERT INTO addresses (address_id, user_id, floor_unit_number, region, province, city_municipality, barangay, street, other_notes, created_at, updated_at) VALUES
(3, 29, '2F C', '07', '0761', '076104', '076104012', 'N/A', '', '2025-11-24 02:50:39', '2025-11-24 02:50:39'),
(4, 52, 'N/A', '17', '1751', '175110', '175110011', 'N/A', 'sa likod ng sementeryo', '2025-11-29 03:38:39', '2025-11-29 03:38:39'),
(5, 26, 'N/A', '03', '0349', '034916', '034916021', 'er', 'We', '2025-12-05 20:32:14', '2025-12-05 20:32:14');

--
-- Dumping data for table categories
--

INSERT INTO categories (category_id, category_name, created_at, updated_at, status) VALUES
(1, 'Mobile Phones & Accessories', '2025-10-10 13:09:17', '2025-10-10 21:09:17', 1),
(2, 'Laptops, Desktops & Monitors', '2025-10-10 13:09:17', '2025-10-10 21:09:17', 1),
(3, 'Audio & Video Equipment', '2025-10-10 13:09:17', '2025-10-10 21:09:17', 1),
(4, 'Smart Home Devices', '2025-10-10 13:09:17', '2025-10-10 21:09:17', 1),
(5, 'Cameras & Photography', '2025-10-10 13:09:17', '2025-10-10 21:09:17', 1),
(6, 'Wearable Technology', '2025-10-10 13:09:17', '2025-10-10 21:09:17', 1);

--
-- Dumping data for table conversations
--

INSERT INTO conversations (conversation_id, buyer_id, seller_id, order_id, created_at, updated_at) VALUES
(3, 26, 24, NULL, '2025-12-05 16:20:45', '2025-12-05 16:21:02'),
(4, 26, 25, 38, '2025-12-05 18:54:58', '2025-12-05 19:45:42');

--
-- Dumping data for table conversation_messages
--

INSERT INTO conversation_messages (message_id, conversation_id, sender_id, message_text, is_read, read_at, created_at) VALUES
(4, 3, 26, 'Hello', 1, '2025-12-06 00:20:59', '2025-12-05 16:20:53'),
(5, 3, 24, 'Hi', 1, '2025-12-06 00:21:12', '2025-12-05 16:21:02'),
(6, 4, 25, 'Hello', 1, '2025-12-06 03:45:38', '2025-12-05 18:55:02'),
(7, 4, 26, 'Hi', 1, '2025-12-06 03:45:55', '2025-12-05 19:45:42');

--
-- Dumping data for table delivery_partners
--

INSERT INTO delivery_partners (partner_id, user_id, full_name, email, phone, vehicle_type, plate_number, region, province, city, barangay, street, drivers_license_path, gov_id_path, created_at, updated_at, status) VALUES
(8, 25, 'Delivery', 'driver@gmail.com', '09692991918', 'motorcycle', 'qweqwe', 'National Capital Region (NCR)', 'City Of Manila', 'San Nicolas', 'Barangay 285', 'qwe', 'static/uploads/delivery_documents\826498360863382.pdf', 'static/uploads/delivery_documents\361721546715047.pdf', '2025-11-15 11:19:04', '2025-11-21 12:45:48', 1);

--
-- Dumping data for table notifications
--

INSERT INTO notifications (notification_id, user_id, order_id, title, message, notification_type, is_read, read_at, created_at) VALUES
(37, 24, 22, 'New order placed', 'User User placed order ckiWlWxN3M (Sub-order ckiWlWxN3M-01) containing 1 item(s): Apple iPhone 17 Pro Max', 'order', 0, NULL, '2025-12-04 09:12:56'),
(38, 24, 23, 'New order placed', 'User User placed order Jpq8pMNmwk (Sub-order Jpq8pMNmwk-01) containing 1 item(s): Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin', 'order', 0, NULL, '2025-12-04 09:16:46'),
(39, 24, 24, 'New order placed', 'User User placed order 6W2rDbou0Y (Sub-order 6W2rDbou0Y-01) containing 1 item(s): Apple iPhone 17 Pro Max', 'order', 0, NULL, '2025-12-04 09:19:44'),
(40, 25, 24, 'Pickup Available', 'Sub-order 6W2rDbou0Y-01 is ready for pickup.', 'system', 0, NULL, '2025-12-04 09:20:52'),
(42, 31, 24, 'Pickup Available', 'Sub-order 6W2rDbou0Y-01 is ready for pickup.', 'system', 0, NULL, '2025-12-04 09:20:52'),
(43, 24, 25, 'New order placed', 'User User placed order 4AlrqsJ06I (Sub-order 4AlrqsJ06I-01) containing 1 item(s): Airpods', 'order', 0, NULL, '2025-12-04 09:52:15'),
(44, 24, 26, 'New order placed', 'User User placed order frTzPxfrIB (Sub-order frTzPxfrIB-01) containing 1 item(s): Apple iPhone 17 Pro Max', 'order', 0, NULL, '2025-12-04 09:57:06'),
(45, 24, 27, 'New order placed', 'User User placed order 7ooHQEYgRi (Sub-order 7ooHQEYgRi-01) containing 1 item(s): SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', 'order', 0, NULL, '2025-12-04 09:57:20'),
(46, 24, 28, 'New order placed', 'User User placed order QcRw0u1WyT (Sub-order QcRw0u1WyT-01) containing 1 item(s): iPhone 13 Pro', 'order', 0, NULL, '2025-12-04 10:04:15'),
(47, 24, 29, 'New order placed', 'User User placed order LeSRJv30Tx (Sub-order LeSRJv30Tx-01) containing 1 item(s): Airpods', 'order', 0, NULL, '2025-12-04 10:08:26'),
(48, 24, 30, 'New order placed', 'User User placed order 0xrs5rl78S (Sub-order 0xrs5rl78S-01) containing 1 item(s): Airpods', 'order', 0, NULL, '2025-12-04 10:08:57'),
(49, 25, 30, 'Pickup Available', 'Sub-order 0xrs5rl78S-01 is ready for pickup.', 'system', 0, NULL, '2025-12-04 10:14:58'),
(51, 31, 30, 'Pickup Available', 'Sub-order 0xrs5rl78S-01 is ready for pickup.', 'system', 0, NULL, '2025-12-04 10:14:58'),
(52, 24, 31, 'New order placed', 'User User placed order Jfc8brVEBE (Sub-order Jfc8brVEBE-01) containing 1 item(s): Selfie Stick Monopod', 'order', 0, NULL, '2025-12-04 10:16:19'),
(53, 24, 32, 'New order placed', 'User User placed order CWUecIDN3O (Sub-order CWUecIDN3O-01) containing 1 item(s): Apple iPhone 17 Pro Max', 'order', 0, NULL, '2025-12-05 16:13:18'),
(54, 24, 33, 'New order placed', 'User User placed order Im0yvcEhGW (Sub-order Im0yvcEhGW-01) containing 1 item(s): Apple iPhone 17 Pro Max', 'order', 0, NULL, '2025-12-05 16:15:04'),
(55, 24, 34, 'New order placed', 'User User placed order ajnm3ma4JB (Sub-order ajnm3ma4JB-01) containing 2 item(s): Apple Airpods, Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5', 'order', 0, NULL, '2025-12-05 16:23:44'),
(56, 24, 35, 'New order placed', 'User User placed order GhNaPNzpbS (Sub-order GhNaPNzpbS-01) containing 1 item(s): Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5', 'order', 0, NULL, '2025-12-05 16:25:01'),
(57, 25, 33, 'Pickup Available', 'Sub-order Im0yvcEhGW-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 16:27:01'),
(58, 25, 34, 'Pickup Available', 'Sub-order ajnm3ma4JB-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 16:27:16'),
(59, 24, 36, 'New order placed', 'User User placed order LEZXebH2ig (Sub-order LEZXebH2ig-01) containing 1 item(s): Apple MacBook Pro 14 Inch Space Grey', 'order', 0, NULL, '2025-12-05 17:15:19'),
(60, 25, 36, 'Pickup Available', 'Sub-order LEZXebH2ig-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 17:36:44'),
(61, 24, 37, 'New order placed', 'User User placed order bIoOKJaxa6 (Sub-order bIoOKJaxa6-01) containing 1 item(s): Apple HomePod Mini Cosmic Grey', 'order', 0, NULL, '2025-12-05 17:50:51'),
(62, 25, 37, 'Pickup Available', 'Sub-order bIoOKJaxa6-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 17:53:04'),
(63, 24, 38, 'New order placed', 'User User placed order zmTWVjHMvs (Sub-order zmTWVjHMvs-01) containing 1 item(s): Huawei Matebook X Pro', 'order', 0, NULL, '2025-12-05 18:31:24'),
(64, 25, 38, 'Pickup Available', 'Sub-order zmTWVjHMvs-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 18:31:52'),
(65, 24, 39, 'New order placed', 'User User placed order afkmOOW8KL (Sub-order afkmOOW8KL-01) containing 1 item(s): Apple MacBook Pro 14 Inch Space Grey', 'order', 0, NULL, '2025-12-05 19:00:32'),
(66, 25, 39, 'Pickup Available', 'Sub-order afkmOOW8KL-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 19:00:48'),
(67, 24, 40, 'New order placed', 'User User placed order eGtomOla2c (Sub-order eGtomOla2c-01) containing 1 item(s): Apple MacBook Pro 14 Inch Space Grey', 'order', 0, NULL, '2025-12-05 19:46:15'),
(68, 25, 40, 'Pickup Available', 'Sub-order eGtomOla2c-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 19:46:47'),
(69, 24, 41, 'New order placed', 'User User placed order 9Rp2qwCB97 (Sub-order 9Rp2qwCB97-01) containing 1 item(s): Apple HomePod Mini Cosmic Grey', 'order', 0, NULL, '2025-12-05 19:53:40'),
(70, 25, 41, 'Pickup Available', 'Sub-order 9Rp2qwCB97-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 19:53:58'),
(71, 24, 42, 'New order placed', 'User User placed order kHjTdbSKBC (Sub-order kHjTdbSKBC-01) containing 1 item(s): Apple Watch Series 4 Gold', 'order', 0, NULL, '2025-12-05 20:00:34'),
(72, 25, 42, 'Pickup Available', 'Sub-order kHjTdbSKBC-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 20:00:50'),
(73, 24, 43, 'New order placed', 'User User placed order 6oFm1oeKZU (Sub-order 6oFm1oeKZU-01) containing 1 item(s): Huawei Matebook X Pro', 'order', 0, NULL, '2025-12-05 20:13:24'),
(74, 25, 43, 'Pickup Available', 'Sub-order 6oFm1oeKZU-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 20:13:45'),
(75, 24, 44, 'New order placed', 'User User placed order c0R1SOUDgR (Sub-order c0R1SOUDgR-01) containing 1 item(s): Apple Watch Series 4 Gold', 'order', 0, NULL, '2025-12-05 20:21:47'),
(76, 25, 44, 'Pickup Available', 'Sub-order c0R1SOUDgR-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 20:22:03'),
(77, 24, 45, 'New order placed', 'User User placed order CFafmJaE5p (Sub-order CFafmJaE5p-01) containing 1 item(s): Oppo A57', 'order', 0, NULL, '2025-12-05 20:28:41'),
(78, 24, 46, 'New order placed', 'User User placed order Bey8jBImWS (Sub-order Bey8jBImWS-01) containing 1 item(s): Oppo A57', 'order', 0, NULL, '2025-12-05 20:32:28'),
(79, 25, 46, 'Pickup Available', 'Sub-order Bey8jBImWS-01 is ready for pickup.', 'system', 0, NULL, '2025-12-05 20:34:00'),
(80, 24, 47, 'New order placed', 'User User placed order 1yrxLmRsTA (Sub-order 1yrxLmRsTA-01) containing 1 item(s): Apple MacBook Pro 14 Inch Space Grey', 'order', 0, NULL, '2026-04-28 13:47:43'),
(81, 24, 48, 'New order placed', 'User User placed order 8yJkNdAWs9 (Sub-order 8yJkNdAWs9-01) containing 1 item(s): Huawei Matebook X Pro', 'order', 0, NULL, '2026-04-28 13:48:23');

--
-- Dumping data for table orders
--

INSERT INTO orders (order_id, user_id, reference, subtotal, shipping_fee, tax_amount, total_amount, cash_type, created_at, updated_at, status) VALUES
(32, 26, 'CWUecIDN3O', 4292470.00, 0.00, 0.00, '4292470.00', 'cod', '2025-12-05 16:13:18', '2025-12-06 00:14:00', 5),
(33, 26, 'Im0yvcEhGW', 80990.00, 0.00, 0.00, '80990.00', 'cod', '2025-12-05 16:15:04', '2025-12-06 00:35:37', 6),
(34, 26, 'ajnm3ma4JB', 238.99, 79.00, 0.00, '317.99', 'cod', '2025-12-05 16:23:44', '2025-12-06 00:34:38', 6),
(35, 26, 'GhNaPNzpbS', 109.00, 79.00, 0.00, '188.00', 'cod', '2025-12-05 16:25:01', '2025-12-06 00:25:01', 1),
(36, 26, 'LEZXebH2ig', 3999.98, 0.00, 0.00, '3999.98', 'cod', '2025-12-05 17:15:19', '2025-12-06 01:15:19', 1),
(37, 26, 'bIoOKJaxa6', 99.99, 79.00, 0.00, '178.99', 'cod', '2025-12-05 17:50:51', '2025-12-06 01:50:51', 1),
(38, 26, 'zmTWVjHMvs', 1399.99, 79.00, 0.00, '1478.99', 'cod', '2025-12-05 18:31:24', '2025-12-06 02:31:24', 1),
(39, 26, 'afkmOOW8KL', 1999.99, 79.00, 0.00, '2078.99', 'cod', '2025-12-05 19:00:32', '2025-12-06 03:00:32', 1),
(40, 26, 'eGtomOla2c', 1999.99, 79.00, 0.00, '2078.99', 'cod', '2025-12-05 19:46:15', '2025-12-06 03:46:15', 1),
(41, 26, '9Rp2qwCB97', 99.99, 79.00, 0.00, '178.99', 'cod', '2025-12-05 19:53:40', '2025-12-06 03:53:40', 1),
(42, 26, 'kHjTdbSKBC', 349.99, 79.00, 0.00, '428.99', 'cod', '2025-12-05 20:00:34', '2025-12-06 04:00:34', 1),
(43, 26, '6oFm1oeKZU', 1399.99, 79.00, 0.00, '1478.99', 'cod', '2025-12-05 20:13:24', '2025-12-06 04:13:24', 1),
(44, 26, 'c0R1SOUDgR', 349.99, 79.00, 0.00, '428.99', 'cod', '2025-12-05 20:21:47', '2025-12-06 04:21:47', 1),
(45, 26, 'CFafmJaE5p', 249.99, 79.00, 0.00, '328.99', 'cod', '2025-12-05 20:28:41', '2025-12-06 04:28:41', 1),
(46, 26, 'Bey8jBImWS', 249.99, 79.00, 0.00, '328.99', 'cod', '2025-12-05 20:32:28', '2025-12-06 04:34:49', 6),
(47, 26, '1yrxLmRsTA', 1999.99, 79.00, 0.00, '2078.99', 'cod', '2026-04-28 13:47:43', '2026-04-28 21:47:56', 5),
(48, 26, '8yJkNdAWs9', 1399.99, 79.00, 0.00, '1478.99', 'cod', '2026-04-28 13:48:23', '2026-04-28 21:48:23', 1);

--
-- Dumping data for table order_items
--

INSERT INTO order_items (order_items_id, product_id, user_id, suborder_id, quantity, variant_type, variant_value, reference, status) VALUES
(60, 32, 26, 31, 53, 'none', NULL, 'CWUecIDN3O', 5),
(61, 32, 26, 32, 1, 'none', NULL, 'Im0yvcEhGW', 6),
(62, 67, 26, 33, 1, 'none', NULL, 'ajnm3ma4JB', 6),
(63, 68, 26, 33, 1, 'none', NULL, 'ajnm3ma4JB', 6),
(64, 68, 26, 34, 1, 'none', NULL, 'GhNaPNzpbS', 8),
(66, 57, 26, 35, 2, 'none', NULL, 'LEZXebH2ig', 4),
(67, 60, 26, 36, 1, 'none', NULL, 'bIoOKJaxa6', 4),
(68, 50, 26, 37, 1, 'none', NULL, 'zmTWVjHMvs', 4),
(69, 57, 26, 38, 1, 'none', NULL, 'afkmOOW8KL', 3),
(70, 57, 26, 39, 1, 'none', NULL, 'eGtomOla2c', 3),
(71, 60, 26, 40, 1, 'none', NULL, '9Rp2qwCB97', 4),
(72, 65, 26, 41, 1, 'none', NULL, 'kHjTdbSKBC', 4),
(73, 50, 26, 42, 1, 'none', NULL, '6oFm1oeKZU', 3),
(74, 65, 26, 43, 1, 'none', NULL, 'c0R1SOUDgR', 4),
(75, 58, 26, 44, 1, 'none', NULL, 'CFafmJaE5p', 1),
(76, 58, 26, 45, 1, 'none', NULL, 'Bey8jBImWS', 6),
(77, 57, 26, 46, 1, 'none', NULL, '1yrxLmRsTA', 5),
(78, 50, 26, 47, 1, 'none', NULL, '8yJkNdAWs9', 1),
(79, 58, 26, NULL, 1, 'none', NULL, '', 1);

--
-- Dumping data for table order_suborders
--

INSERT INTO order_suborders (suborder_id, order_id, seller_id, reference, status, subtotal, shipping_fee, tax_amount, total_amount, created_at, updated_at, pickup_status, pickup_rider_id, pickup_claimed_at, pickup_completed_at) VALUES
(31, 32, 24, 'CWUecIDN3O-01', 5, 4292470.00, 0.00, 0.00, 4292470.00, '2025-12-05 16:13:18', '2025-12-05 16:14:00', 0, NULL, NULL, NULL),
(32, 33, 24, 'Im0yvcEhGW-01', 6, 80990.00, 0.00, 0.00, 80990.00, '2025-12-05 16:15:04', '2025-12-05 20:19:54', 4, 25, '2025-12-06 00:31:21', '2025-12-06 00:33:59'),
(33, 34, 24, 'ajnm3ma4JB-01', 6, 238.99, 79.00, 0.00, 317.99, '2025-12-05 16:23:44', '2025-12-05 20:19:54', 4, 25, '2025-12-06 00:31:19', '2025-12-06 00:33:58'),
(34, 35, 24, 'GhNaPNzpbS-01', 8, 109.00, 79.00, 0.00, 188.00, '2025-12-05 16:25:01', '2025-12-05 16:25:36', 0, NULL, NULL, NULL),
(35, 36, 24, 'LEZXebH2ig-01', 4, 3999.98, 0.00, 0.00, 3999.98, '2025-12-05 17:15:19', '2025-12-05 20:19:54', 4, 25, '2025-12-06 01:38:17', '2025-12-06 01:50:02'),
(36, 37, 24, 'bIoOKJaxa6-01', 4, 99.99, 79.00, 0.00, 178.99, '2025-12-05 17:50:51', '2025-12-05 20:19:54', 4, 25, '2025-12-06 01:53:35', '2025-12-06 01:58:41'),
(37, 38, 24, 'zmTWVjHMvs-01', 4, 1399.99, 79.00, 0.00, 1478.99, '2025-12-05 18:31:24', '2025-12-05 20:19:54', 4, 25, '2025-12-06 02:32:23', '2025-12-06 02:41:46'),
(38, 39, 24, 'afkmOOW8KL-01', 3, 1999.99, 79.00, 0.00, 2078.99, '2025-12-05 19:00:32', '2025-12-05 20:19:54', 3, 25, '2025-12-06 03:06:34', NULL),
(39, 40, 24, 'eGtomOla2c-01', 3, 1999.99, 79.00, 0.00, 2078.99, '2025-12-05 19:46:15', '2025-12-05 20:19:54', 3, 25, '2025-12-06 03:46:58', NULL),
(40, 41, 24, '9Rp2qwCB97-01', 4, 99.99, 79.00, 0.00, 178.99, '2025-12-05 19:53:40', '2025-12-05 20:19:54', 4, 25, '2025-12-06 03:54:42', '2025-12-06 03:57:11'),
(41, 42, 24, 'kHjTdbSKBC-01', 4, 349.99, 79.00, 0.00, 428.99, '2025-12-05 20:00:34', '2025-12-05 20:01:13', 4, 25, '2025-12-06 04:01:06', '2025-12-06 04:01:13'),
(42, 43, 24, '6oFm1oeKZU-01', 3, 1399.99, 79.00, 0.00, 1478.99, '2025-12-05 20:13:24', '2025-12-05 20:14:07', 3, 25, '2025-12-06 04:13:57', NULL),
(43, 44, 24, 'c0R1SOUDgR-01', 4, 349.99, 79.00, 0.00, 428.99, '2025-12-05 20:21:47', '2025-12-05 20:22:44', 4, 25, '2025-12-06 04:22:23', '2025-12-06 04:22:44'),
(44, 45, 24, 'CFafmJaE5p-01', 1, 249.99, 79.00, 0.00, 328.99, '2025-12-05 20:28:41', '2025-12-05 20:28:41', 0, NULL, NULL, NULL),
(45, 46, 24, 'Bey8jBImWS-01', 6, 249.99, 79.00, 0.00, 328.99, '2025-12-05 20:32:28', '2025-12-05 20:34:49', 4, 25, '2025-12-06 04:34:19', '2025-12-06 04:34:38'),
(46, 47, 24, '1yrxLmRsTA-01', 5, 1999.99, 79.00, 0.00, 2078.99, '2026-04-28 13:47:43', '2026-04-28 13:47:56', 0, NULL, NULL, NULL),
(47, 48, 24, '8yJkNdAWs9-01', 1, 1399.99, 79.00, 0.00, 1478.99, '2026-04-28 13:48:23', '2026-04-28 13:48:23', 0, NULL, NULL, NULL);

--
-- Dumping data for table products
--

INSERT INTO products (product_id, user_id, category_id, product_name, description, price, qty, variant_type, variant_values, created_at, updated_at, status) VALUES
(32, 24, 1, 'Apple iPhone 17 Pro Max', '<h2><span style="color: rgb(46, 51, 70);">Product Details</span></h2><p><br></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/80cd44831a19253c14f6eb830a1b26e4.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/1dbc9b2ef7c52352408e3c0beae31df1.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/8c42cef9c30446124509669d948b90af.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/64a001478f5cd9065fb5a6c4a71fd15e.png_2200x2200q80.png_.webp"></span></p><p><br></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/c0b4efd0f3ce1da650422899ffbe0b1b.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/76de24d2ff93f12e9f941e846fada57c.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/73a7f1256278c34439951a3c54e0edd4.jpg_2200x2200q80.jpg_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/50e473eb89cca70d6ec3e4df0e27af3e.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/87e7620216c15f9f32b55d5731435d9f.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/c204fbe19fbbb63b1b8021103e49887d.png_2200x2200q80.png_.webp"></span></p><p><br></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/e97527268995294d6daa6f8770901767.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/7cfba9a4754b3f581af287915427652b.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/3e24b76cee8aaed81f5c2d58e96b099e.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/b1c8997c6cfc747aa954aa432911b435.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/b050366f1a96f33b5f65c0fc9d4c35e1.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/c7f89cc62c4dbb91a9b939c21713290e.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/880aadadf89019cca70000e57f130950.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/24d2aefe15e95a43ea2d149e1beb0887.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/8ea36614a94011741a1fb958711b793e.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/da9b8f3be3ef0b12cbbb07550ae5f4d8.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/ccfb20cadbf5da035ea5d7b2fb9866af.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/21f559c2569f3eddb9b346669f16a18e.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/c4bf697f0edfb379181a997496265fcf.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/979035c76489749bef93199110f652ad.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/93c9f5bf387d6953cca1f1a08b868291.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/81feb19f29430f960f40b2e3e9b5bcec.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/a9a4f5faa4bfb4ea30bd09b4dac3bbbb.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/f127c2aa195bd036efb8fe7a8111581a.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/e8c5ecca99f756b72e7854c9e4d38bb1.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/0deaadf6fa752bec2c9fcc64756482ed.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/0c4f25ca7628b53233a9f6e781330f21.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/870d578f10702ee762ff522810eb496e.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/a520fa4c12c5be0881e52bdd6858b447.png_2200x2200q80.png_.webp"></span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"><img src="https://img.lazcdn.com/g/p/866fa2c461a654a3db922b009e61ee9d.png_2200x2200q80.png_.webp"></span></p><p><br></p><h2><span style="background-color: rgb(255, 255, 255); color: rgb(46, 51, 70);">Specifications of Apple iPhone 17 Pro Max</span></h2><ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="background-color: rgb(255, 255, 255); color: rgb(117, 117, 117);">Brand</span></li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">Apple</span></li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="background-color: rgb(255, 255, 255); color: rgb(117, 117, 117);">SKU</span></li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">5260093111_PH-31227369038</span></li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="background-color: rgb(255, 255, 255); color: rgb(117, 117, 117);">Model</span></li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">Apple iPhone 17 Pro Max</span></li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="background-color: rgb(255, 255, 255); color: rgb(117, 117, 117);">Warranty Type</span></li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">International Manufacturer Warranty</span></li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="background-color: rgb(255, 255, 255); color: rgb(117, 117, 117);">Warranty</span></li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">1 Year</span></li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="background-color: rgb(255, 255, 255); color: rgb(117, 117, 117);">Delivery Option Instant</span></li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">Yes</span></li></ol><p><span style="background-color: rgb(255, 255, 255); color: rgb(117, 117, 117);">What’s in the box</span></p><p><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">iPhone with iOS&nbsp;26,USB-C Charge Cable (1m),Documentation</span></p><p class="ql-align-center"><br></p><p><br></p>', 80990.00, 30, 'none', NULL, '2025-11-18 15:09:27', '2025-12-06 00:47:09', 2),
(50, 24, 1, 'Huawei Matebook X Pro', '<p>The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.</p>', 1399.99, 486, 'none', NULL, '2025-11-24 13:38:03', '2025-12-06 04:13:43', 1),
(57, 24, 2, 'Apple MacBook Pro 14 Inch Space Grey', '<p>The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple''s M1 Pro chip for exceptional performance and a stunning Retina display.</p>', 1999.99, 19, 'none', NULL, '2025-11-24 13:38:15', '2025-12-06 03:46:44', 1),
(58, 24, 1, 'Oppo A57', '<p>The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice.</p>', 249.99, 32, 'none', NULL, '2025-11-24 13:38:16', '2025-12-06 04:33:57', 1),
(59, 24, 2, 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', '<p>Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer''s limited warranty</p>', 114.00, 47, 'none', NULL, '2025-11-24 13:38:19', '2025-11-24 21:38:19', 1),
(60, 24, 4, 'Apple HomePod Mini Cosmic Grey', '<p>The Apple HomePod Mini in Cosmic Grey is a compact smart speaker that delivers impressive audio and integrates seamlessly with the Apple ecosystem for a smart home experience.</p>', 99.99, 38, 'none', NULL, '2025-11-24 13:38:20', '2025-12-06 03:53:55', 1),
(61, 24, 1, 'iPhone 12 Silicone Case with MagSafe Plum', '<p>The iPhone 12 Silicone Case with MagSafe in Plum is a stylish and protective case designed for the iPhone 12. It features MagSafe technology for easy attachment of accessories.</p>', 29.99, 14, 'none', NULL, '2025-11-24 13:38:23', '2025-11-24 21:38:23', 1),
(62, 24, 4, 'Realme C35', '<p>The Realme C35 is a budget-friendly smartphone with a focus on providing essential features for everyday use. It offers a reliable performance and user-friendly experience.</p>', 149.99, 13, 'none', NULL, '2025-11-24 13:38:25', '2025-11-24 21:38:25', 1),
(63, 24, 5, 'iPad Mini 2021 Starlight', '<p>The iPad Mini 2021 in Starlight is a compact and powerful tablet from Apple. Featuring a stunning Retina display, powerful A-series chip, and a sleek design, it offers a premium tablet experience.</p>', 499.99, 39, 'none', NULL, '2025-11-24 13:38:27', '2025-11-24 21:38:27', 1),
(64, 24, 1, 'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin', '<p>21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz</p>', 599.00, 22, 'none', NULL, '2025-11-24 13:38:29', '2025-11-24 21:38:29', 1),
(65, 24, 6, 'Apple Watch Series 4 Gold', '<p>The Apple Watch Series 4 in Gold is a stylish and advanced smartwatch with features like heart rate monitoring, fitness tracking, and a beautiful Retina display.</p>', 349.99, 27, 'none', NULL, '2025-11-24 13:38:30', '2025-12-06 04:22:01', 1),
(66, 24, 1, 'Samsung Galaxy S10', '<p>The Samsung Galaxy S10 is a flagship device featuring a dynamic AMOLED display, versatile camera system, and powerful performance. It represents innovation and excellence in smartphone technology.</p>', 699.99, 27, 'none', NULL, '2025-11-24 13:38:32', '2025-11-24 21:38:32', 1),
(67, 24, 3, 'Apple Airpods', '<p>The Apple Airpods offer a seamless wireless audio experience. With easy pairing, high-quality sound, and Siri integration, they are perfect for on-the-go listening.</p>', 129.99, 43, 'none', NULL, '2025-11-24 13:38:33', '2025-12-06 00:25:52', 1),
(68, 24, 2, 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5', '<p>3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.</p>', 109.00, 35, 'none', NULL, '2025-11-24 13:38:35', '2025-12-06 00:25:52', 1),
(69, 24, 1, 'Apple Airpower Wireless Charger', '<p>The Apple AirPower Wireless Charger provides a convenient way to charge your compatible Apple devices wirelessly. Simply place your devices on the charging mat for effortless charging.</p>', 79.99, 39, 'none', NULL, '2025-11-24 13:38:37', '2025-11-24 21:38:37', 1),
(70, 24, 1, 'iPhone X', '<p>The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.</p>', 899.99, 38, 'none', NULL, '2025-11-24 13:38:38', '2025-11-24 21:38:38', 1),
(71, 24, 1, 'Samsung Galaxy Tab White', '<p>The Samsung Galaxy Tab in White is a sleek and versatile Android tablet. With a vibrant display, long-lasting battery, and a range of features, it offers a great user experience for various tasks.</p>', 349.99, 22, 'none', NULL, '2025-11-24 13:38:40', '2025-11-24 21:38:40', 1),
(72, 24, 2, 'Oppo F19 Pro Plus', '<p>The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities. It boasts advanced photography features and a powerful performance for a premium user experience.</p>', 399.99, 46, 'none', NULL, '2025-11-24 13:38:41', '2025-11-24 21:38:41', 1),
(73, 24, 2, 'New DELL XPS 13 9300 Laptop', '<p>The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.</p>', 1499.99, 47, 'none', NULL, '2025-11-24 13:38:43', '2025-11-24 21:38:43', 1),
(74, 24, 3, 'Apple MagSafe Battery Pack', '<p>The Apple MagSafe Battery Pack is a portable and convenient way to add extra battery life to your MagSafe-compatible iPhone. Attach it magnetically for a secure connection.</p>', 99.99, 11, 'none', NULL, '2025-11-24 13:38:45', '2025-11-24 21:38:45', 1),
(75, 24, 1, 'Samsung Galaxy Tab S8 Plus Grey', '<p>The Samsung Galaxy Tab S8 Plus in Grey is a high-performance Android tablet by Samsung. With a large AMOLED display, powerful processor, and S Pen support, it''s ideal for productivity and entertainment.</p>', 599.99, 24, 'none', NULL, '2025-11-24 13:38:46', '2025-11-24 21:38:46', 1),
(76, 24, 4, 'Realme XT', '<p>The Realme XT is a feature-rich smartphone with a focus on camera technology. It comes equipped with advanced camera sensors, delivering high-quality photos and videos for photography enthusiasts.</p>', 349.99, 40, 'none', NULL, '2025-11-24 13:38:47', '2025-11-24 21:38:47', 1),
(77, 24, 3, 'Monopod', '<p>The Monopod is a versatile camera accessory for stable and adjustable shooting. Perfect for capturing selfies, group photos, and videos with ease.</p>', 19.99, 20, 'none', NULL, '2025-11-24 13:38:49', '2025-11-24 21:38:49', 1),
(78, 24, 1, 'Apple AirPods Max Silver', '<p>The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio, adaptive EQ, and active noise cancellation. Experience immersive sound in style.</p>', 549.99, 9, 'none', NULL, '2025-11-24 13:38:51', '2025-11-24 21:38:51', 1),
(79, 24, 1, 'Vivo X21', '<p>The Vivo X21 is a premium smartphone with a focus on cutting-edge technology. It features an in-display fingerprint sensor, a high-resolution display, and advanced camera capabilities.</p>', 499.99, 18, 'none', NULL, '2025-11-24 13:38:52', '2025-11-24 21:38:52', 1),
(80, 24, 3, 'Vivo S1', '<p>The Vivo S1 is a stylish and mid-range smartphone offering a blend of design and performance. It features a vibrant display, capable camera system, and reliable functionality.</p>', 249.99, 33, 'none', NULL, '2025-11-24 13:38:54', '2025-11-24 21:38:54', 1),
(81, 24, 2, 'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ', '<p>49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag</p>', 999.99, 35, 'none', NULL, '2025-11-24 13:38:56', '2025-11-24 21:38:56', 1),
(82, 24, 1, 'Selfie Lamp with iPhone', '<p>The Selfie Lamp with iPhone is a portable and adjustable LED light designed to enhance your selfies and video calls. Attach it to your iPhone for well-lit photos.</p>', 14.99, 10, 'none', NULL, '2025-11-24 13:38:58', '2025-11-24 21:38:58', 1),
(83, 24, 1, 'Samsung Galaxy S7', '<p>The Samsung Galaxy S7 is a flagship smartphone known for its sleek design and advanced features. It features a high-resolution display, powerful camera, and robust performance.</p>', 299.99, 36, 'none', NULL, '2025-11-24 13:38:59', '2025-11-24 21:38:59', 1),
(84, 24, 2, 'Test', '<p>qwe</p>', 1000.00, 4, 'sizes', 'Small, Large', '2025-12-05 16:49:36', '2025-12-06 00:49:36', 1);

--
-- Dumping data for table product_attachments
--

INSERT INTO product_attachments (product_attachment_id, product_id, attachment, created_at, updated_at, status) VALUES
(53, 31, 'uploads/products/e9a073ad152f4726a5f296fccc44091f.jpg', '2025-11-16 18:30:13', '2025-11-17 02:30:13', 1),
(54, 32, 'uploads/products/100d52bcd5c043d5a2bdb444c1b923c1.webp', '2025-11-18 15:09:27', '2025-11-18 23:09:27', 1),
(57, 34, 'uploads/products/c973f485dd4e494f873c95015e98bf85.jpg', '2025-11-24 13:31:26', '2025-11-24 21:31:26', 1),
(58, 35, 'uploads/products/e606c0235f5846d5b4cd5afae48467e5.jpg', '2025-11-24 13:31:29', '2025-11-24 21:31:29', 1),
(59, 36, 'uploads/products/4a9cb82058094bc88a43685f1d568e68.jpg', '2025-11-24 13:31:32', '2025-11-24 21:31:32', 1),
(60, 37, 'uploads/products/f82693fa2b1c45f98ce370c081008f15.jpg', '2025-11-24 13:31:36', '2025-11-24 21:31:36', 1),
(61, 38, 'uploads/products/f3d831340df54cc4bf9e0606d35e0184.jpg', '2025-11-24 13:31:39', '2025-11-24 21:31:39', 1),
(62, 39, 'uploads/products/a0e03fc16f9d47e8b8e5572f8f84354a.jpg', '2025-11-24 13:31:42', '2025-11-24 21:31:42', 1),
(63, 40, 'uploads/products/f642aecf5f3249f2aae7ca0d54e5b52f.jpg', '2025-11-24 13:37:46', '2025-11-24 21:37:46', 1),
(64, 41, 'uploads/products/a950c86145de4443917ec75aeefa8336.jpg', '2025-11-24 13:37:48', '2025-11-24 21:37:48', 1),
(65, 42, 'uploads/products/3e76a4dc58884556ac539eed00836df4.jpg', '2025-11-24 13:37:50', '2025-11-24 21:37:50', 1),
(66, 43, 'uploads/products/e306e85f9bec4ed7b69e2521adc3705d.jpg', '2025-11-24 13:37:52', '2025-11-24 21:37:52', 1),
(67, 44, 'uploads/products/9ec517842694450fa1f232b4dd02b96f.jpg', '2025-11-24 13:37:53', '2025-11-24 21:37:53', 1),
(68, 45, 'uploads/products/b9c71a6491894f228589d64819ed4867.jpg', '2025-11-24 13:37:55', '2025-11-24 21:37:55', 1),
(69, 46, 'uploads/products/626f8dd565664aed95cecbc617aedd04.jpg', '2025-11-24 13:37:57', '2025-11-24 21:37:57', 1),
(70, 47, 'uploads/products/1b3337ad4c5340d1b0fa085740d069d1.jpg', '2025-11-24 13:37:58', '2025-11-24 21:37:58', 1),
(71, 48, 'uploads/products/5500228f52144eba8a6d4b231f7a4c0a.jpg', '2025-11-24 13:38:00', '2025-11-24 21:38:00', 1),
(72, 49, 'uploads/products/69e1938a4fd547d19b1f6af1a4089313.jpg', '2025-11-24 13:38:02', '2025-11-24 21:38:02', 1),
(73, 50, 'uploads/products/f2174f4dc3054642aec97fb3958a04fa.jpg', '2025-11-24 13:38:03', '2025-11-24 21:38:03', 1),
(74, 51, 'uploads/products/2c753f12c90a44d98962a48c2a9fdee0.jpg', '2025-11-24 13:38:05', '2025-11-24 21:38:05', 1),
(75, 52, 'uploads/products/76894abd62124c1ba74cff8ebe89460e.jpg', '2025-11-24 13:38:07', '2025-11-24 21:38:07', 1),
(76, 53, 'uploads/products/8dab46ee9d9044918969478c454b691b.jpg', '2025-11-24 13:38:08', '2025-11-24 21:38:08', 1),
(77, 54, 'uploads/products/5b459799f83347f5ab063644ecdf880d.jpg', '2025-11-24 13:38:10', '2025-11-24 21:38:10', 1),
(78, 55, 'uploads/products/3ac9f89ba91f45a8af3ca69ba814ba57.jpg', '2025-11-24 13:38:12', '2025-11-24 21:38:12', 1),
(79, 56, 'uploads/products/de7ae09de7994d4b800082d3b2b3333c.jpg', '2025-11-24 13:38:14', '2025-11-24 21:38:14', 1),
(80, 57, 'uploads/products/c697ebdedd68449ba2b4178c2569854e.jpg', '2025-11-24 13:38:15', '2025-11-24 21:38:15', 1),
(81, 58, 'uploads/products/8e4cae9b2f4540409ee2f2bb150f9a5d.jpg', '2025-11-24 13:38:16', '2025-11-24 21:38:16', 1),
(82, 59, 'uploads/products/ae24ef06e3ec4a4aa4d963f23f16ca15.jpg', '2025-11-24 13:38:19', '2025-11-24 21:38:19', 1),
(83, 60, 'uploads/products/26a9056d046a4803b91c8defc52fe11e.jpg', '2025-11-24 13:38:20', '2025-11-24 21:38:20', 1),
(84, 61, 'uploads/products/a59c054cf83d4330a20e96373402a1da.jpg', '2025-11-24 13:38:23', '2025-11-24 21:38:23', 1),
(85, 62, 'uploads/products/66e663a9ab4043ea80e6cce6c36c4c5f.jpg', '2025-11-24 13:38:25', '2025-11-24 21:38:25', 1),
(86, 63, 'uploads/products/0f021630023940529d433d5c3ce809e3.jpg', '2025-11-24 13:38:27', '2025-11-24 21:38:27', 1),
(87, 64, 'uploads/products/2ebc8f877b5243c29cb0d75306895ae3.jpg', '2025-11-24 13:38:29', '2025-11-24 21:38:29', 1),
(88, 65, 'uploads/products/2292fd5affb4459ea94d4b831843de17.jpg', '2025-11-24 13:38:30', '2025-11-24 21:38:30', 1),
(89, 66, 'uploads/products/c65edea507e548ccb398551f3e7b2fd1.jpg', '2025-11-24 13:38:32', '2025-11-24 21:38:32', 1),
(90, 67, 'uploads/products/b8a39085881849c99219b7594ef076f8.jpg', '2025-11-24 13:38:33', '2025-11-24 21:38:33', 1),
(91, 68, 'uploads/products/62400d3dea804511ae7225a3eebfe416.jpg', '2025-11-24 13:38:35', '2025-11-24 21:38:35', 1),
(92, 69, 'uploads/products/29d4a90371da46b99b6960f06eee2510.jpg', '2025-11-24 13:38:37', '2025-11-24 21:38:37', 1),
(93, 70, 'uploads/products/e147c2c23c4a40b2b452fe467e968c06.jpg', '2025-11-24 13:38:38', '2025-11-24 21:38:38', 1),
(94, 71, 'uploads/products/c25764a287a0466ead30324d302360bd.jpg', '2025-11-24 13:38:40', '2025-11-24 21:38:40', 1),
(95, 72, 'uploads/products/11a197d6ad36458d8e2824ac3138c508.jpg', '2025-11-24 13:38:41', '2025-11-24 21:38:41', 1),
(96, 73, 'uploads/products/bc6974708d8b4b8abb4633db30d1d6a4.jpg', '2025-11-24 13:38:43', '2025-11-24 21:38:43', 1),
(97, 74, 'uploads/products/20091e710cf44d33bd5fe914c9b7ca8d.jpg', '2025-11-24 13:38:45', '2025-11-24 21:38:45', 1),
(98, 75, 'uploads/products/9fb8661e663845a6a22091eda6bc147f.jpg', '2025-11-24 13:38:46', '2025-11-24 21:38:46', 1),
(99, 76, 'uploads/products/95342b3cc81246768f5d09c7f2ea2198.jpg', '2025-11-24 13:38:47', '2025-11-24 21:38:47', 1),
(100, 77, 'uploads/products/7180da0ec09a421e8641fba9697f47a0.jpg', '2025-11-24 13:38:49', '2025-11-24 21:38:49', 1),
(101, 78, 'uploads/products/1b3dcf2f078d49568432f62ba8720f1e.jpg', '2025-11-24 13:38:51', '2025-11-24 21:38:51', 1),
(102, 79, 'uploads/products/e2ead3c9a7514f3cbf6e7feab1d32f41.jpg', '2025-11-24 13:38:52', '2025-11-24 21:38:52', 1),
(103, 80, 'uploads/products/f9025a77a2184551a498d9765e449a66.jpg', '2025-11-24 13:38:54', '2025-11-24 21:38:54', 1),
(104, 81, 'uploads/products/73fe6780a6ab46699bb55210074c64f5.jpg', '2025-11-24 13:38:56', '2025-11-24 21:38:56', 1),
(105, 82, 'uploads/products/76baf06ff1c946dcb98f76b535ae74b8.jpg', '2025-11-24 13:38:58', '2025-11-24 21:38:58', 1),
(106, 83, 'uploads/products/5bd3dec9add4454eb63bb9b36f360136.jpg', '2025-11-24 13:38:59', '2025-11-24 21:38:59', 1),
(107, 84, 'uploads/products/05f30307ba4349eaad19f17ab8d3c32f.png', '2025-12-05 16:49:36', '2025-12-06 00:49:36', 1);

--
-- Dumping data for table product_reviews
--

INSERT INTO product_reviews (review_id, product_id, user_id, order_items_id, reference, rating, comment, created_at) VALUES
(3, 32, 26, 61, 'Im0yvcEhGW', 4, 'Goods', '2025-12-05 16:36:53');

--
-- Dumping data for table roles
--

INSERT INTO roles (role_id, name) VALUES
(1, 'Admin'),
(2, 'Buyer'),
(3, 'Seller'),
(4, 'Rider');

--
-- Dumping data for table seller_details
--

INSERT INTO seller_details (seller_detail_id, user_id, store_name, description, region, province, city, barangay, street, gov_id_path, business_permit_path, created_at, updated_at, status) VALUES
(9, 24, 'Seller', 'imissher', 'Region XII (SOCCSKSARGEN)', 'Cotabato (North Cotabato)', 'Pigkawayan', 'Lower Pangangkalan', 'qwe', 'static/uploads/seller_documents\465302976581719.pdf', 'static/uploads/seller_documents\612746791708541.pdf', '2025-11-15 11:18:25', '2025-12-02 18:15:02', 1);

--
-- Dumping data for table users
--

INSERT INTO users (user_id, role_id, firstname, lastname, email, password, phone, email_verified, email_verified_at, email_code_hash, email_code_expires_at, email_code_attempts, email_code_last_sent_at, created_at, updated_at, status, otp_last_sent_at) VALUES
(8, 1, 'Admin', 'Risu', 'admin@gmail.com', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', '09876543217', 1, NULL, NULL, NULL, 0, NULL, '2025-10-12 14:03:40', '2025-11-29 01:11:28', 1, NULL),
(24, 3, 'Seller', '', 'Seller@gmail.com', '81954b0388567d0ef7ab6185715f02967dcb6ad8bba755b43207f7c2da065649', '09692991918', 1, NULL, NULL, NULL, 0, NULL, '2025-11-15 11:18:25', '2025-12-03 02:15:02', 1, NULL),
(25, 4, 'Delivery', '', 'driver@gmail.com', '81954b0388567d0ef7ab6185715f02967dcb6ad8bba755b43207f7c2da065649', '09692991918', 1, NULL, NULL, NULL, 0, NULL, '2025-11-15 11:19:04', '2025-11-29 10:39:58', 1, NULL),
(26, 2, 'User', 'User', 'User@gmail.com', '81954b0388567d0ef7ab6185715f02967dcb6ad8bba755b43207f7c2da065649', '09692991918', 1, NULL, NULL, NULL, 0, NULL, '2025-11-16 16:45:05', '2025-11-29 10:40:10', 1, NULL);

--
-- Dumping data for table wishlists
--

INSERT INTO wishlists (wishlist_id, user_id, product_id, created_at) VALUES
(4, 26, 32, '2025-12-06 00:10:49'),
(5, 26, 50, '2025-12-06 00:10:50'),
(6, 26, 64, '2025-12-06 00:10:59');


-- Primary keys and indexes

ALTER TABLE public.addresses ADD CONSTRAINT addresses_pkey PRIMARY KEY (address_id);

CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON public.addresses (user_id);

ALTER TABLE public.categories ADD CONSTRAINT categories_pkey PRIMARY KEY (category_id);

ALTER TABLE public.conversations ADD CONSTRAINT conversations_pkey PRIMARY KEY (conversation_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_conversations_uq_conversation_pair ON public.conversations (buyer_id,seller_id);

CREATE INDEX IF NOT EXISTS idx_conversations_idx_conversations_buyer ON public.conversations (buyer_id);

CREATE INDEX IF NOT EXISTS idx_conversations_idx_conversations_seller ON public.conversations (seller_id);

CREATE INDEX IF NOT EXISTS idx_conversations_idx_conversations_order ON public.conversations (order_id);

ALTER TABLE public.conversation_messages ADD CONSTRAINT conversation_messages_pkey PRIMARY KEY (message_id);

CREATE INDEX IF NOT EXISTS idx_conversation_messages_idx_conv_messages_conversation ON public.conversation_messages (conversation_id);

CREATE INDEX IF NOT EXISTS idx_conversation_messages_idx_conv_messages_sender ON public.conversation_messages (sender_id);

ALTER TABLE public.delivery_partners ADD CONSTRAINT delivery_partners_pkey PRIMARY KEY (partner_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_partners_uniq_partner_email ON public.delivery_partners (email);

CREATE INDEX IF NOT EXISTS idx_delivery_partners_delivery_partners_user_id ON public.delivery_partners (user_id);

ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);

CREATE INDEX IF NOT EXISTS idx_notifications_notifications_user_id ON public.notifications (user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_notifications_order_id ON public.notifications (order_id);

ALTER TABLE public.orders ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders (user_id);

ALTER TABLE public.order_items ADD CONSTRAINT order_items_pkey PRIMARY KEY (order_items_id);

CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON public.order_items (product_id);

CREATE INDEX IF NOT EXISTS idx_order_items_user_id ON public.order_items (user_id);

CREATE INDEX IF NOT EXISTS idx_order_items_suborder_id ON public.order_items (suborder_id);

CREATE INDEX IF NOT EXISTS idx_order_items_idx_order_items_wishlist ON public.order_items (user_id);

ALTER TABLE public.order_suborders ADD CONSTRAINT order_suborders_pkey PRIMARY KEY (suborder_id);

CREATE INDEX IF NOT EXISTS idx_order_suborders_order_id ON public.order_suborders (order_id);

CREATE INDEX IF NOT EXISTS idx_order_suborders_seller_id ON public.order_suborders (seller_id);

ALTER TABLE public.payments ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_id);

CREATE INDEX IF NOT EXISTS idx_payments_order_id ON public.payments (order_id);

ALTER TABLE public.products ADD CONSTRAINT products_pkey PRIMARY KEY (product_id);

CREATE INDEX IF NOT EXISTS idx_products_FK_products_category ON public.products (category_id);

CREATE INDEX IF NOT EXISTS idx_products_FK_products_user ON public.products (user_id);

ALTER TABLE public.product_attachments ADD CONSTRAINT product_attachments_pkey PRIMARY KEY (product_attachment_id);

CREATE INDEX IF NOT EXISTS idx_product_attachments_FK_product_attachments ON public.product_attachments (product_id);

ALTER TABLE public.product_reviews ADD CONSTRAINT product_reviews_pkey PRIMARY KEY (review_id);

CREATE INDEX IF NOT EXISTS idx_product_reviews_idx_product ON public.product_reviews (product_id);

CREATE INDEX IF NOT EXISTS idx_product_reviews_idx_user ON public.product_reviews (user_id);

CREATE INDEX IF NOT EXISTS idx_product_reviews_idx_order_item ON public.product_reviews (order_items_id);

ALTER TABLE public.reviews ADD CONSTRAINT reviews_pkey PRIMARY KEY (review_id);

CREATE INDEX IF NOT EXISTS idx_reviews_reviews_order_id ON public.reviews (order_id);

CREATE INDEX IF NOT EXISTS idx_reviews_reviews_product_id ON public.reviews (product_id);

CREATE INDEX IF NOT EXISTS idx_reviews_reviews_user_id ON public.reviews (user_id);

ALTER TABLE public.roles ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);

ALTER TABLE public.seller_details ADD CONSTRAINT seller_details_pkey PRIMARY KEY (seller_detail_id);

CREATE INDEX IF NOT EXISTS idx_seller_details_seller_details_user_id ON public.seller_details (user_id);

ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_uniq_users_email ON public.users (email);

CREATE INDEX IF NOT EXISTS idx_users_FK_users ON public.users (role_id);

ALTER TABLE public.wishlists ADD CONSTRAINT wishlists_pkey PRIMARY KEY (wishlist_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_wishlists_uq_user_product ON public.wishlists (user_id,product_id);

CREATE INDEX IF NOT EXISTS idx_wishlists_idx_wishlists_user ON public.wishlists (user_id);

CREATE INDEX IF NOT EXISTS idx_wishlists_idx_wishlists_product ON public.wishlists (product_id);


-- Foreign keys

ALTER TABLE public.conversations ADD CONSTRAINT fk_conversations_buyer FOREIGN KEY (buyer_id) REFERENCES public.users (user_id) ON DELETE CASCADE;

ALTER TABLE public.conversations ADD CONSTRAINT fk_conversations_order FOREIGN KEY (order_id) REFERENCES public.orders (order_id) ON DELETE SET NULL;

ALTER TABLE public.conversations ADD CONSTRAINT fk_conversations_seller FOREIGN KEY (seller_id) REFERENCES public.users (user_id) ON DELETE CASCADE;


-- updated_at trigger replacement for MySQL ON UPDATE current_timestamp()

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_addresses_updated_at ON public.addresses;
CREATE TRIGGER set_addresses_updated_at
BEFORE UPDATE ON public.addresses
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_categories_updated_at ON public.categories;
CREATE TRIGGER set_categories_updated_at
BEFORE UPDATE ON public.categories
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_conversations_updated_at ON public.conversations;
CREATE TRIGGER set_conversations_updated_at
BEFORE UPDATE ON public.conversations
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_delivery_partners_updated_at ON public.delivery_partners;
CREATE TRIGGER set_delivery_partners_updated_at
BEFORE UPDATE ON public.delivery_partners
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_orders_updated_at ON public.orders;
CREATE TRIGGER set_orders_updated_at
BEFORE UPDATE ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_order_suborders_updated_at ON public.order_suborders;
CREATE TRIGGER set_order_suborders_updated_at
BEFORE UPDATE ON public.order_suborders
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_products_updated_at ON public.products;
CREATE TRIGGER set_products_updated_at
BEFORE UPDATE ON public.products
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_product_attachments_updated_at ON public.product_attachments;
CREATE TRIGGER set_product_attachments_updated_at
BEFORE UPDATE ON public.product_attachments
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_reviews_updated_at ON public.reviews;
CREATE TRIGGER set_reviews_updated_at
BEFORE UPDATE ON public.reviews
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_seller_details_updated_at ON public.seller_details;
CREATE TRIGGER set_seller_details_updated_at
BEFORE UPDATE ON public.seller_details
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_users_updated_at ON public.users;
CREATE TRIGGER set_users_updated_at
BEFORE UPDATE ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

COMMIT;
